image: experoinc/ci-frontend-node8

pipelines:
  default:
    - step:
        name: Deploy
        caches:
          - node
        script:
          - yarn
          - yarn run deploy
  branches:
    '{master,develop}':
      - step:
          name: Build and test
          caches:
            - node
          script:
            - yarn
            - yarn run lint
            - yarn run build