image: experoinc/ci-frontend-node8

pipelines:
  branches:
    '{master,develop}':
      - step:
          name: Build and test
          caches:
            - node
          script:
            - yarn
            - yarn run lint
            - yarn run build